### PR TITLE
Fix Caps Lock LEDs once and for all

### LINKED ISSUE #2471: USB_LED_CAPS_LOCK not working with LED anymore [Ergodox EZ]
Maybe @ezuk can share a little light on this. I could imagine there might be some terminology changes that I'm not aware of. I searched the open/closed issues, but haven't found a thing.

@jackhumbert [commented in 2016](https://github.com/qmk/qmk_firmware/issues/92#issuecomment-172629034) confirming this works for all things OLKB. I'm 100% sure this ought to work for the EZ, too, since I used the code below for over about a year and it worked… but not anymore:

    // Runs constantly in the background, in a loop.
    void matrix_scan_user(void) {
      ergodox_board_led_off();
      ergodox_right_led_1_off();
      ergodox_right_led_2_off();
      ergodox_right_led_3_off();
      // This used to work 2017-09-06, but not anymore. Can't find a solution.
      if (host_keyboard_leds() & (1<<USB_LED_CAPS_LOCK)) {
        ergodox_right_led_1_on ();
      }
    };

My board and led's work. Just tested that it's all red when going the reverse way:

    if (host_keyboard_leds() & (1<<USB_LED_CAPS_LOCK)) {
      ergodox_right_led_3_on ();
    } else {
      ergodox_right_led_1_on ();
    }

### PR DESCRIPTION
**Pull request by fauxpark**
## Description
The status LEDs don't light up/light up incorrectly on Linux in certain circumstances. This is because, if NKRO is enabled it will send two LED states, one for the 6KRO interface, and one for the NKRO interface. QMK interprets the NKRO report ID as the LED state and turn on the num lock and scroll lock LEDs.

If we have two bytes, that probably means the first is a report ID. The 6KRO interface may or may not have one, but the NKRO interface always does, so we need to check this regardless of whether `KEYBOARD_SHARED_EP` is defined.

The status LEDs now function correctly on Windows 10, macOS 10.14 and Ubuntu 18.10 under the following conditions:

 - `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=no`
 - `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=yes`, NKRO off
 - `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=yes`, NKRO on
 - `KEYBOARD_SHARED_EP=yes`, `NKRO_ENABLE=no`
 - `KEYBOARD_SHARED_EP=yes`, `NKRO_ENABLE=yes`, NKRO off
 - `KEYBOARD_SHARED_EP=yes`, `NKRO_ENABLE=yes`, NKRO on

## Types of changes

- [ ] Core
- [x] Bugfix
- [ ] New Feature
- [ ] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* Fixes #2471

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: tmk_core/protocol/lufa/lufa.c [hunk 1]
```diff
@@ -517,17 +517,20 @@ void EVENT_USB_Device_ControlRequest(void)
...
+
+                    if (Endpoint_BytesInEndpoint() == 2) {
+                      uint8_t report_id = REPORT_ID_KEYBOARD;
+
+                      if (keyboard_protocol) {
+                        report_id = Endpoint_Read_8();
+                      }
+
+                      if (report_id == REPORT_ID_KEYBOARD || report_id == REPORT_ID_NKRO) {
+                          keyboard_led_stats = Endpoint_Read_8();
```
Comment (vomindoraan) [inline tmk_core/protocol/lufa/lufa.c]:
```suggestion
                        keyboard_led_stats = Endpoint_Read_8();
```
Indentation. I'd also kill the two empty lines above, it's readable enough without them.

Comment (fauxpark) [reply tmk_core/protocol/lufa/lufa.c]: I prefer to have empty lines between consecutive block statements and before keywords like break and return, personally I think that is more readable. I wish QMK had a more defined code style :(

**Comment by DidierLoiseau** [comment]
Works perfectly fine for me on Ubuntu 18.10, with all combinations of `KEYBOARD_SHARED_EP` and `NKRO_ENABLE`.

File: tmk_core/protocol/lufa/lufa.c (hunk 1 above)
Comment (drashna) [reply tmk_core/protocol/lufa/lufa.c]: @fauxpark Open an issue/PR to improve it, please! :)
https://docs.qmk.fm/#/contributing?id=coding-conventions

**Comment by drashna** [comment]
Thanks!

**Comment by adzenith** [comment]
I just came here to say I've been trying way too long to figure out why my caps lock light didn't work (macOS Mojave) and this fixed it like magic. Thanks @fauxpark!
