### PR TITLE
Fix connection issue in split keyboards when slave and OLED display are connected via I2C, fix #9335

### LINKED ISSUE #9335: [Bug] Bug on split slave side using I2C comms and OLED
I'm having an issue getting my handwired split board working with I2C communication and an OLED.

There's a repeatable issue that only affects the slave, which is why I consider it a bug. Not an address conflict or config issue as far as I can tell. Something funky about split keyboard slave just not behaving over I2C if the OLED is also enabled.

How to reproduce:
If I start with OLED_DRIVER_ENABLE=OFF and flash that to the slave half, then turn it ON and flash the master half, everything works as expected, I get input from both halves and OLED works. But then if I flash the same with it ON to both halves, I stop getting input from the slave, while the OLED still works. The behavior follows whichever is the slave if I switch which side the USB is plugged in. 

Troubleshooting steps:
Sometimes I see the rgb animation slow down a ton on the master which seems to indicate an I2C timeout. Not sure how else to troubleshoot. A few posts seem to indicate this should be totally doable, but don't want to get as deep into it as something like the Helix fork to get working.

- Keyboard:  
   - Split 5x6 Dactyl variant, handwired
   - 2x Pro Micro
   - I2C between halves
   - RGB lighting + split rgb enabled
   - 1306 OLED on single half

 - AVR GCC version: 8.3.0
 - QMK Firmware version: 0.8.192

### PR DESCRIPTION
**Pull request by osenchenko**
## Description

Now in split keyboards it is impossble to use I2C OLED display and I2C for communication beetween halves.
This described in #9335

PR disables calls to OLED display from slave half in case I2C used for OLED display and for communication beetwen halves. This restores normal communication between halves.
PR addresses the case when only one OLED display is used in split keyboard. When using two OLED displays on both halves of keyboard it is impossible to use I2C. Serial commmunication between halves should be used.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #9335

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by drashna** [comment]
Honestly, I'm not a fan of this.  Specifically, that the fix is in tmk_core, rather than the oled_driver.c file.  You coud have a `is_keyboard_master` check there, and be much less obtrusive.

**Comment by osenchenko** [comment]
Sounds resonable.  Should I close this PR and make new PR or make changes in current PR (and make changes in osenchenko:fix_9335 branch)?

**Comment by drashna** [comment]
In theory, you could just revert the existing changes and add the new changes to this PR, and that would be fine.

**Comment by osenchenko** [comment]
Made changes to oled_driver.c. I've tested latest changes on my split keyboard, which uses i2c for communication and i2c oled display. It works as expected.

File: drivers/oled/oled_driver.c [hunk 1]
```diff
@@ -152,6 +154,10 @@ static void InvertCharacter(uint8_t *cursor) {
 }
 
 bool oled_init(uint8_t rotation) {
+#ifdef USE_I2C
```
Comment (drashna) [inline drivers/oled/oled_driver.c:157]:
```suggestion
#if defined(USE_I2C) && defined(SPLIT_KEYBOARD)
```

Also, this should probably go into oled_task, (line 687~)

Comment (osenchenko) [reply drivers/oled/oled_driver.c]: I  am not sure. It's up to you. If you wish, I can add changes to oled_task.
I agree that adding check in oled_task gives more confidence that code will not execute on the slave half.

I decided not to change oled_task because the logic in oled_task is based on oled_initialized variable.  
Oled_initialized set true only at the end of oled_init
https://github.com/qmk/qmk_firmware/blob/ce47d1907a02f857f764ddc396053dd4c56a837f/drivers/oled/oled_driver.c#L220
So if we return early from oled_init, then  oled_initialized is always false.
And oled_task will always return early
https://github.com/qmk/qmk_firmware/blob/ce47d1907a02f857f764ddc396053dd4c56a837f/drivers/oled/oled_driver.c#L688

**Review by drashna — APPROVED** [review]
I was going to say something about `oled_task` (I think I did actually), but double checking the code... if it's not init'ed, then it doesn't actually call the code, so this is all that is needed then. 

So, looks good!

**Comment by tzarc** [comment]
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

**Review by tzarc — APPROVED** [review]
