### PR TITLE
Fix RGB_DISABLE_TIMEOUT overflow warning (#9866)

### LINKED ISSUE #9866: [Bug] Expansion of RGB_DISABLE_TIMEOUT overflows
## Describe the Bug

User is able to define `RGB_DISABLE_AFTER_TIMEOUT` in their config which roughly equates to a number of seconds of inactivity before RGB lights are disabled. This bug limits this to a maximum 27, as anything higher causes an overflow and compiler error.

```
Compiling: quantum/rgb_matrix.c
quantum/rgb_matrix.c: In function 'rgb_matrix_task':
quantum/rgb_matrix.c:61:60: error: integer overflow in expression of type 'int' results in '-31936' [-Werror=overflow]
 #    define RGB_DISABLE_TIMEOUT (RGB_DISABLE_AFTER_TIMEOUT * 1200)
                                                            ^
quantum/rgb_matrix.c:392:39: note: in expansion of macro 'RGB_DISABLE_TIMEOUT'
         (rgb_anykey_timer > (uint32_t)RGB_DISABLE_TIMEOUT) ||
                                       ^~~~~~~~~~~~~~~~~~~

```

The code above expands to`(uint32_t)(28 * 1200)` (if `RGB_DISABLE_AFTER_TIMEOUT` is defined as `28`) with the cast outside the parenthesis. ~Removing the parenthesis on line 61 fixes this issue and compiles without problem, but I am not sure if it is the most correct solution as this macro is used elsewhere.~  
~~#    define RGB_DISABLE_TIMEOUT RGB_DISABLE_AFTER_TIMEOUT * 1200~~ I'm dumb.

## System Information

 - Keyboard:  dz65rgb
   - Revision:  v2
 - Operating system: Win10
 - AVR GCC version: 8.3.0
 - ARM GCC version: 8.3.1 20190703
 - QMK Firmware version: 0.9.46

### PR DESCRIPTION
**Pull request by BeefaloKing**
## Description

Forces long integer math in the expansion of `RGB_DISABLE_TIMEOUT` when a config file uses the deprecated define `RGB_DISABLE_AFTER_TIMEOUT` to prevent overflow with values greater than 27.
```C
#    define RGB_DISABLE_TIMEOUT (RGB_DISABLE_AFTER_TIMEOUT * 1200ul)
```

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #9866 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/rgb_matrix.c [hunk 1]
```diff
@@ -58,7 +58,7 @@ const point_t k_rgb_matrix_center = RGB_MATRIX_CENTER;
 // ------------------------------------------
 
 #if defined(RGB_DISABLE_AFTER_TIMEOUT) && !defined(RGB_DISABLE_TIMEOUT)
-#    define RGB_DISABLE_TIMEOUT (RGB_DISABLE_AFTER_TIMEOUT * 1200)
+#    define RGB_DISABLE_TIMEOUT (RGB_DISABLE_AFTER_TIMEOUT * 1200ul)
```
Comment (fauxpark) [inline quantum/rgb_matrix.c:61]:
```suggestion
#    define RGB_DISABLE_TIMEOUT (RGB_DISABLE_AFTER_TIMEOUT * 1200UL)
```
