### PR TITLE
[Bug] Fix Underglow keycode processing

### LINKED ISSUE #24792: [Bug] (Minor) Compiler warning when RGB_MATRIX_DISABLE_SHARED_KEYCODES and RGB_MATRIX_ENABLE are both defined
### Describe the Bug

With `RGB_MATRIX_DISABLE_SHARED_KEYCODES` and `RGB_MATRIX_ENABLED` both defined, I get a compiler warning (which becomes an error under default settings) in _process_underglow.c_ at line 19 for unused variable `shifted`.

I have come to realize this by following a recommendation I had found in the docs, to add `RGB_MATRIX_DISABLE_SHARED_KEYCODES` to my _config.h_ as it turns off a (soon to be) deprecated behavior. I have managed to work around this issue by adding one more guard around the line declaring `shifted`, which works for my particular constellation of flags, but likely to break others.

### Keyboard Used

hotdox76v2

### Link to product page (if applicable)

_No response_

### Operating System

_No response_

### qmk doctor Output

_No response_

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by drashna**
## Description

If RGB Matrix is enabled and `RGB_MATRIX_DISABLE_SHARED_KEYCODES` is defined, `shifted` is set but never used, causing unused variable errors. 

## Types of Changes

- [x] Core
- [x] Bugfix

## Issues Fixed or Closed by This PR

* Fixes #24792

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

File: quantum/process_keycode/process_underglow.c [hunk 1]
```diff
@@ -16,7 +16,8 @@
 
 bool process_underglow(uint16_t keycode, keyrecord_t *record) {
     if (record->event.pressed) {
-        uint8_t shifted = get_mods() & MOD_MASK_SHIFT;
+        __attribute__((unused)) const uint8_t shifted = get_mods() & MOD_MASK_SHIFT;
```
Comment (fauxpark) [inline quantum/process_keycode/process_underglow.c:19]:
```suggestion
#if defined(RGBLIGHT_ENABLE) || (defined(RGB_MATRIX_ENABLE) && !defined(RGB_MATRIX_DISABLE_SHARED_KEYCODES))
        const uint8_t shifted = get_mods() & MOD_MASK_SHIFT;
#endif
```

**Review by fauxpark — CHANGES_REQUESTED** [review]
