### PR TITLE
Fix leftover reference to previous AW20216S EN pin definition

### LINKED ISSUE #23973: [Bug] GMMK Numpad Matrix LEDs not working
### Describe the Bug

I've just received a brand new GMMK Numpad. After flashing the latest QMK firmware onto it, the RGB matrix LEDs are no longer working.

### Keyboard Used

gmmk/numpad

### Link to product page (if applicable)

https://www.gloriousgaming.com/products/gmmk-numpad-keyboard

### Operating System

Linux

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.5
Ψ QMK home: /home/kh/qmk_firmware
Ψ Detected Linux (Arch Linux).
Ψ Userspace enabled: False
Ψ Git branch: fix-gmmk-numpad-led-enable
Ψ Repo version: 0.25.8
Ψ - Latest fix-gmmk-numpad-led-enable: 2024-06-21 18:58:34 +0200 (d2f7ce39d6) -- fix invalid led enable pin for gmmk numpad
Ψ - Latest upstream/master: 2024-06-20 01:08:57 -0700 (a6ef34cd16) -- [Keyboard] fixes for ZSA Voyager (#23912)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2024-06-20 01:08:57 -0700 (a6ef34cd16) -- [Keyboard] fixes for ZSA Voyager (#23912)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 14.1.0
Ψ Found avr-gcc version 14.1.0
⚠ We do not recommend avr-gcc newer than 8. Downgrading to 8.x is recommended.
Ψ Found avrdude version 7.3
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-04-03 20:39:24 +0800 --  (77cb0a4f)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

The issue seems to stem from #23067 via commit 0b7df03. After consolidating the EN pins of the AW20216S controller, there was still a reference to the old definition for the gmmk/numpad keyboard.

### PR DESCRIPTION
**Pull request by horvatkevin**
See issue https://github.com/qmk/qmk_firmware/issues/23973 for exact details on how the error has surfaced.

## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes #23973

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: keyboards/gmmk/numpad/numpad.c [hunk 1]
```diff
@@ -107,7 +107,7 @@ led_config_t g_led_config = {{
 	2, 2, 2, 2, 2, 2, 2
 } };
 
-#    ifdef AW20216S_PW_EN_PIN_1
+#    ifdef AW20216S_PW_EN_PIN
 
 void keyboard_pre_init_user(void) {
```
Comment (zvecr) [inline keyboards/gmmk/numpad/numpad.c:112]: While we are changing this file, please can you update the lines to the following:

```c
void keyboard_pre_init_kb(void) {
    wait_ms(2000);
    gpio_set_pin_output(AW20216S_PW_EN_PIN);
    gpio_write_pin_high(AW20216S_PW_EN_PIN);

    keyboard_pre_init_user();
}
```

**Review by zvecr — CHANGES_REQUESTED** [review]

File: keyboards/gmmk/numpad/numpad.c (hunk 1 above)
Comment (horvatkevin) [reply keyboards/gmmk/numpad/numpad.c:112]: Sure.

I do not know the code base very well, but shouldn't the user facing initialization `keyboard_pre_init_user()` be called regardless of the definition of `AW20216S_PW_EN_PIN`?

Comment (zvecr) [reply keyboards/gmmk/numpad/numpad.c:112]: There is a default implementation, <https://github.com/qmk/qmk_firmware/blob/master/quantum/keyboard.c#L279-L287>.

This suggested change maintains the expected semantics.

Comment (horvatkevin) [reply keyboards/gmmk/numpad/numpad.c]: Makes sense. Thanks for the hint.

**Review by zvecr — APPROVED** [review]

**Review by fauxpark — APPROVED** [review]
Whoops
