### PR TITLE
Ignore space cadet key release when caps word is active

### LINKED ISSUE #17546: [Bug] When turning on Caps Word, my keyboard types a number for some reason
Whenever I activate Caps Word, my keyboard immediately types a zero or a nine. I activate Caps Word by pressing both of my shift keys, which are also Space Cadet shift keys.

## Describe the Bug

Whenever I activate Caps Word, my keyboard immediately types a zero or a nine.

## System Information

**Keyboard:** Ergodox EZ
**Revision (if applicable):** N/A
**Operating system:** EndeavourOS Sway edition
**`qmk doctor` output:** 
```
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: /home/anomalocaris/qmk_firmware
Ψ Detected Linux.
Ψ Git branch: personal-keymap
Ψ Repo version: 0.14.23
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 12.1.0
Ψ Found avr-gcc version 8.3.0
Ψ Found avrdude version 7.0
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go
```

**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [ ] Other:

## Additional Context
I have updated my fork of QMK earlier today, about 5 hours ago.

### PR DESCRIPTION
**Pull request by p3l6**
## Description

If using `BOTH_SHIFTS_TURNS_ON_CAPS_WORD` and Space cadet, activating Caps word before the tapping term expires produces either an unwanted `0` or `9`, depending on which shift was pressed first. A deeper explanation of the cause can be found in the linked issue below. 

In this change, when shift if released, I check to see if caps word is enabled, and then perform the same space cadet code branch as if the tapping term had expired. That is to say, releasing the modifier without typing the parenthesis. This works because caps word is processed first, so when entering caps word mode, the flag will already be set when processing space cadet. In the case that a shift key is tapped to exit caps word, the flag will be disabled before space cadet processes, and the key will be processed normally. 

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #17546

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by getreuer** [comment]
@p3l6 thank you for contributing this fix!

My impression is this fix makes sense. It is delicate logic how Caps Word and Space Cadet features interoperate. To avoid regression where some future change breaks this behavior again, it would be a good idea to add a unit test to cover `BOTH_SHIFTS_TURNS_ON_CAPS_WORD` + Space Cadet.

In case you are new to testing in QMK, here are a few notes. I suggest: 

1. Add a test case covering this change in [tests/caps_word/test_caps_word.cpp](https://github.com/qmk/qmk_firmware/blob/master/tests/caps_word/test_caps_word.cpp).
2. Test it by running `make test:caps_word`.

Tests written using the [GoogleTest](https://google.github.io/googletest/) framework. Take a look at the existing tests in the same file examples of how GoogleTest is used in QMK to simulate and test key events.

File: quantum/process_keycode/process_space_cadet.c [hunk 1]
```diff
@@ -93,7 +93,11 @@ void perform_space_cadet(keyrecord_t *record, uint16_t sc_keycode, uint8_t holdM
             register_mods(MOD_BIT(holdMod));
         }
     } else {
+#ifdef BOTH_SHIFTS_TURNS_ON_CAPS_WORD
+        if (sc_last == holdMod && timer_elapsed(sc_timer) < GET_TAPPING_TERM(sc_keycode, record) && !is_caps_word_on()) {
+#else
         if (sc_last == holdMod && timer_elapsed(sc_timer) < GET_TAPPING_TERM(sc_keycode, record)) {
+#endif
```
Comment (sigprof) [inline quantum/process_keycode/process_space_cadet.c:100]: This change effectively blocks taps of *all* Space Cadet keys while Caps Word is active.  Because Space Cadet keys are customizable and can be used also with other modifiers than just Shift, this restriction may not be desired.

An alternative way to fix the problem might be:

- Add a function to reset the Space Cadet state (the same thing happens when any other key is pressed while a Space Cadet key is held down):
```c
void reset_space_cadet(void) {
    sc_last = 0;
}
```
- Call `reset_space_cadet()` from the Caps Word code when the press of both shifts is detected.

This way only the last tap of Space Cadet Shift which activates Caps Word would be forcibly converted to a hold, and other usage of Space Cadet keys during Caps Word would remain undisturbed.

Comment (p3l6) [reply quantum/process_keycode/process_space_cadet.c]: Thanks for this additional context and write-up, I've re-worked the change in the way you suggested.

**Comment by p3l6** [comment]
@getreuer When I went to add a new test case, I noticed that the existing cases already covered this combination, but had an exception to wait for the Tapping term to expire to work around the issue. I think removing tapping term in the existing tests could be sufficient, but let me know if you think an explicitly named case would still be good.

I checked that 
* Adjusting the test without the fix does fail due to the extra `0` produced
* Tests pass with the fix

**Comment by sigprof** [comment]
Another feature which probably won't work together with Space Cadet is `CAPS_WORD_INVERT_ON_SHIFT` (the code for that feature actually intercepts `KC_LSFT`, `KC_RSFT` and the `MT()` and `OSM()` keycodes for the same modifiers and handles the modifier change in a special way instead of registering the modifier as usual).  Not sure how to fix that properly though without introducing some more assumptions about the space cadet configuration (in theory it is possible to configure `QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN` and `QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE` to use a completely different modifier, and detecting whether the intended space cadet action is actually a tap or a hold is not possible outside of the space cadet code).

**Comment by p3l6** [comment]
I am also not familiar enough (or at all) with `CAPS_WORD_INVERT_ON_SHIFT` to want to attempt any similar fix myself.

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]
