### PR TITLE
Fixed print statement after enabling 32-bit layers

### LINKED ISSUE #25026: [Bug] Enabling 32-bit layers and console prevents compilation
### Describe the Bug

When adding `#define LAYER_STATE_32BIT` to my config.h to increase the number of layers available, I was not able to compile the firmware while `CONSOLE_ENABLE` is also defined.

This is due to the fact that the print statement expects and unsigned int, but `layer_state_t` is now defined as an unsigned long. Changing the print statement to expect an unsigned long allows everything to work perfectly with both features enabled.

### PR DESCRIPTION
**Pull request by dabstractor**
Enabling both LAYER_STATE_32BIT and CONSOLE_ENABLE currently causes QMK not to compile due to a mismatch in the types expected in a print statement in quantum/command.c.

## Description

I simply added a definition check around the print statement and handled both print statments independently.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes #25026

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/command.c [hunk 1]
```diff
@@ -243,7 +243,11 @@ static void print_status(void) {
 
 #if !defined(NO_PRINT) && !defined(USER_PRINT)
 static void print_eeconfig(void) {
+#if defined(LAYER_STATE_32BIT)
+    xprintf("eeconfig:\ndefault_layer: %lu\n", eeconfig_read_default_layer());
+#else
     xprintf("eeconfig:\ndefault_layer: %u\n", eeconfig_read_default_layer());
+#endif
```
Comment (drashna) [inline quantum/command.c:250]: Currently, the default layer is stored only in an 8-bit variable so I'd like to limit to that, for consistency rather than adding a preprocessor here. 
```suggestion
    xprintf("eeconfig:\ndefault_layer: %u\n", (uint8_t)eeconfig_read_default_layer());
```
Though, I'm not sure that this is the best way to go about this.

(also, noticed that action_layer.c has a couple of debug prints that also error out, if you define `ACTION_DEBUG` with the 32 bit define)

Comment (tzarc) [reply quantum/command.c:250]: `%u` on AVR and ARM are likely two different bitwidths.
The resulting `layer_state_t` can also be a single layer value converted to full-width bitmask (assuming `DEFAULT_LAYER_STATE_IS_VALUE_NOT_BITMASK`), so downcasting to uint8_t is incorrect here.

Suggest using `%lu` unconditionally, and casting to `(long int)` to ensure it matches both AVR and ARM expectations.

Comment (dabstractor) [reply quantum/command.c]: Thank you for the assist. It works well for me, I've updated the PR with your suggestion

**Review by tzarc — APPROVED** [review]

**Review by drashna — APPROVED** [review]
