### PR TITLE
Removed print call to resolve  #6364

### LINKED ISSUE #6364: this debug call causes the buffer to overflow, please remove
## Describe the Bug
buffer overflow occasionally, keyboard attempts to write to console, which may or may not exist, this causes the board to become unresponsive, and need a dis/reconnect to the computer.

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

removing console from the build options seemed to fix this, but i think its easier to not try to print to console during a time sensitive interrupt

### PR DESCRIPTION
**Pull request by jakergrossman**
## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  #6364

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: tmk_core/protocol/xt_interrupt.c [hunk 1]
```diff
@@ -37,6 +37,7 @@ POSSIBILITY OF SUCH DAMAGE.
 */
 
 #include <stdbool.h>
+#include <stdio.h>
```
Comment (fauxpark) [inline tmk_core/protocol/xt_interrupt.c]:
```suggestion
```

This should be removed, and the print.h include replaced with debug.h (I can't add a suggestion there as it's outside of this hunk).
