### PR TITLE
Fix AUTOGEN and Travis Compiled Push scripts 

### LINKED ISSUE #4953: Default Preonic rev 3 file is a hex file. This should be a .bin file.
The autogen script in QMK Toolbox does not work properly for Preonic v3. It generates a .hex file when it should be a .bin. I believe the [keyboards] page on the docs also points to an incorrect download file.
preonic-v3-default

### PR DESCRIPTION
**Pull request by drashna**
## Description
Currently, when you add `AUTOGEN=true` to the make command, it compiles the file as a `hex` regardless of the architecture.  This is wrong, and generates `hex` files for ARM boards like the Planck Rev6.  This file isn't flashable, as far as I'm aware. 

This changes the AUTOGEN script to use the extension agnostic `FIRMWARE_FORMAT` instead of hard coding it to `hex`.   This means that the correct `bin` file is copied to the keymap folder, instead of a `hex`, when appropriate.

This also changes the Travis Compiled script to look for both hex and bin files, and push those to `qmk.fm/compiled` automatically.

## Types of changes

- [x] Core
- [x] Bugfix
- [ ] New Feature
- [x] Enhancement/Optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/Layout/Userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by this PR

* Fixes #4953 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: util/travis_compiled_push.sh [hunk 1]
```diff
@@ -69,10 +69,9 @@ if [[ "$TRAVIS_COMMIT_MESSAGE" != *"[skip build]"* ]] ; then
 	# rm -f compiled/*.hex
 
 	# ignore errors here
-	for file in ../qmk_firmware/keyboards/*/keymaps/*/*_default.hex; do mv -v "$file" "compiled/${file##*/}" || true; done
-	for file in ../qmk_firmware/keyboards/*/*/keymaps/*/*_default.hex; do mv -v "$file" "compiled/${file##*/}" || true; done
-	for file in ../qmk_firmware/keyboards/*/*/*/keymaps/*/*_default.hex; do mv -v "$file" "compiled/${file##*/}" || true; done
-	for file in ../qmk_firmware/keyboards/*/*/*/*/keymaps/*/*_default.hex; do mv -v "$file" "compiled/${file##*/}" || true; done
+  # In theory, this is more flexible, and will allow for additional expansion of additional types of files and other names
+  mv -t compiled ../qmk_firmware/keyboards/*(*|*/*|*/*/*|*/*/*/*|*/*/*/*/*)/keymaps/*/*_default.*(hex|bin) || true
```
Comment (skullydazed) [inline util/travis_compiled_push.sh]:
```suggestion
  mv -t compiled ../qmk_firmware/keyboards/*(/*|/*/*|/*/*/*|/*/*/*/*)/keymaps/*/*_default.*(hex|bin) || true
```

File: tmk_core/arm_atsam.mk [hunk 2]
```diff
@@ -54,3 +54,7 @@ EXTRALIBDIRS =
 bin: $(BUILD_DIR)/$(TARGET).hex
 	$(OBJCOPY) -Iihex -Obinary $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
 	$(COPY) $(BUILD_DIR)/$(TARGET).bin $(TARGET).bin;
+	@if $(AUTOGEN); then \
+		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).hex | true; \
```
Comment (skullydazed) [inline tmk_core/arm_atsam.mk]:
```suggestion
		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).$(FIRMWARE_FORMAT) | true; \
```

File: tmk_core/avr.mk [hunk 3]
```diff
@@ -235,6 +235,10 @@ avrdude-loop: $(BUILD_DIR)/$(TARGET).hex check-size cpfirmware
 # Convert hex to bin.
 bin: $(BUILD_DIR)/$(TARGET).hex
 	$(OBJCOPY) -Iihex -Obinary $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
+	@if $(AUTOGEN); then \
+		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).hex | true; \
```
Comment (skullydazed) [inline tmk_core/avr.mk]:
```suggestion
		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).$(FIRMWARE_FORMAT) | true; \
```

File: tmk_core/chibios.mk [hunk 4]
```diff
@@ -256,3 +256,7 @@ st-link-cli: $(BUILD_DIR)/$(TARGET).hex sizeafter
 
 bin: $(BUILD_DIR)/$(TARGET).bin sizeafter
 	$(COPY) $(BUILD_DIR)/$(TARGET).bin $(TARGET).bin;
+	@if $(AUTOGEN); then \
+		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).hex | true; \
```
Comment (skullydazed) [inline tmk_core/chibios.mk]:
```suggestion
		$(REMOVE) $(KEYMAP_PATH)/$(TARGET).$(FIRMWARE_FORMAT) | true; \
```

File: util/travis_compiled_push.sh (hunk 1 above)
Comment (drashna) [reply util/travis_compiled_push.sh]: I think that will exclude the base folder.   But I'm not sure/will have to check.

File: tmk_core/arm_atsam.mk (hunk 2 above)
Comment (drashna) [reply tmk_core/arm_atsam.mk]: This needs to remove the hex file, so it's not copied to `qmk.fm/compiled`.  
Otherwise, `travis_compiled_push.sh` will push a hex file where we need bin files for those boards.

Comment (drashna) [reply tmk_core/arm_atsam.mk]: Specifically, I tried this, in the core "hex" target, and it caused this issue:
https://travis-ci.org/qmk/qmk_firmware/builds/490409457#L1203-L1208

And:
https://travis-ci.org/qmk/qmk_firmware/builds/490409457#L1303-L1305

File: util/travis_compiled_push.sh (hunk 1 above)
Comment (drashna) [reply util/travis_compiled_push.sh]: Unfortunately, neither appears to work for anything but the first sub-directory.

So unless somebody more skilled with this stuff (eg, not me) has a suggestion, this may be better:
```suggestion
  mv -t compiled ../qmk_firmware/keyboards/*/keymaps/*/*_default.*(hex|bin) || true
  mv -t compiled ../qmk_firmware/keyboards/*/*/keymaps/*/*_default.*(hex|bin) || true
  mv -t compiled ../qmk_firmware/keyboards/*/*/*/keymaps/*/*_default.*(hex|bin) || true
  mv -t compiled ../qmk_firmware/keyboards/*/*/*/*/keymaps/*/*_default.*(hex|bin) || true
  mv -t compiled ../qmk_firmware/keyboards/*/*/*/*/*/keymaps/*/*_default.*(hex|bin) || true
```

Comment (drashna) [reply util/travis_compiled_push.sh]: Also, the reason for this change was so that we can get both the bin and hex files in one go, without having to have 4-5 commands for each format (so 8 or 10 commands here).

Also, this makes it more modular, so we could add other keymaps to the compiled list, such as VIA keymaps.

Comment (skullydazed) [reply util/travis_compiled_push.sh]: Maybe something like this then?

```suggestion
  find ../qmk_firmware/keyboards -name \*_default.(hex|bin) | grep /keymaps/ | xargs mv -t compiled || true
```

Comment (drashna) [reply util/travis_compiled_push.sh]: It doesn't like `(hex|bin)`. 

```
bash: syntax error near unexpected token `('
```

Adding ?, *,  ^  doesn't help.

Comment (drashna) [reply util/travis_compiled_push.sh]: @vomindoraan Since you're good with this stuff, from what I've seen, any suggestions?

Comment (skullydazed) [reply util/travis_compiled_push.sh]: We can just pass -name twice, see my edited suggestion.

Comment (drashna) [reply util/travis_compiled_push.sh]: That gives me "missing file operand" :(

**Comment by drashna** [comment]
The last commit drastically changes things by removing AUTOGEN, as it doesn't appear to be needed. 

The reasoning behind this, is that it looks like AUTOGEN was initially added for the old makefile system  (where a `makefile` was in every folder, and called there).   I could be wrong about this .... but ....
This appears to make things much simpler, as all the compiled firmware images reside in the qmk_firmware directory, in their final, compiled form.  

This way, a simple `mv` command can be used here, rather than a complex script.   This also makes the command more flexible, and opens it up to easily adding via images, for instance. (eg, look for `qmk_firmware/*_*(default|via).*(hex|bin)`, in theory)
