### PR TITLE
Keep pressed keys on layer state change (fixes #2053, #2279)

### LINKED ISSUE #2053: Already pressed key gets released when switching layers
Full disclosure: I'm a newbie using an Ergodox EZ here, haven't actually built my own firmware (yet). I have a key configured as **Ins** on **Layer 0**. I also have another key mapped to MO(1). If I press and hold Ins, as soon as I press the layer toggle key Ins up is sent, but the key is still being physically held down. Wouldn't it be useful if QMK could remember the layer where key-down occurred, and preserve the context through to key-up?

### LINKED ISSUE #2279: Is it possible to keep the input from the previous layer when switching?
Its pretty hard to describe. Lets say im playing a game, and holding W. If i switch to a layer while holding w, is it possible to lock that input until i come back to the same layer? I tried doing it with kc_trans but that did not work. The second i switch layers (while holding w) - w is no longer sent as input. My poker worked like that, and i was wondering if its possible with qmk.

### PR DESCRIPTION
**Pull request by vomindoraan**
This allows pressed keys to stay pressed when a layer change occurs.

Say you're playing a game and you're holding W to run forward. You need to access a menu or skill that's bound to F4. You have that set on a momentary layer, so you try pressing Fn+4 — but as soon as you press Fn, QMK resets the W key and you stop moving forward, even though you're still holding the key.
For a visual explanation of the issue, see [this video](https://youtu.be/O4AKOX7F5SA?t=4h30m34s).

This fixes the problem by not resetting held keys when the layer state changes. It relies on the _prevent stuck modifiers_ implementation keeping track of which key was pressed on which layer and resetting them accordingly so that no keys end up stuck. As a consequence, it's disabled when `STRICT_LAYER_RELEASE` is defined, for backwards compatibility reasons.

I've tested this using every combination of pressing/releasing keys, mods and layers I could think of, and I haven't been able to find any issues (keys getting stuck or similar). I've also made sure that it doesn't affect the existing behavior of `clear_keyboard_but_mods` or the behavior of `layer_state_set` when `STRICT_LAYER_RELEASE` is enabled.

This fixes #2053, and fixes #2279.

### CODE REVIEW

**Comment by vomindoraan** [comment]
In light of the recent merge of #3107, I've changed the code to check for `STRICT_LAYER_RELEASE` instead of `PREVENT_STUCK_MODIFIERS` (as that is now obsolete).

The merge also means that this improved behavior of keys not being reset on layer change will be the default for all keyboards (once this PR is merged as well), without needing to manually define anything! 🎉 

Finally, I also took the chance to replace all occurrences of the somewhat unreadable:
`#if !defined(NO_ACTION_LAYER) && !defined(STRICT_LAYER_RELEASE)`
 with [logically equivalent](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) code:
`#if defined(NO_ACTION_LAYER) || defined(STRICT_LAYER_RELEASE)`.

**Comment by drashna** [comment]
Hmm, testing this out ..... MOD TAP does NOT work correctly on this.   

Eg, I use `CTL_T(KC_SLSH)` on my Iris.  If I hold down the key to get control, switch layers, and then release the key, it does not unregister the mod. 

Same with OSM's, and shifted keys get stuck, as well. 

so there may be some special handling that is needed here.

**Comment by vomindoraan** [comment]
@drashna You're right, something went wrong either with the latest changes I made, or this PR and the new default behavior don't play well together (though I'm not sure why that would be the case). Will investigate.

**Comment by vomindoraan** [comment]
@drashna It looks like it was that last commit. Could you try again now?

**Comment by vomindoraan** [comment]
Oh boy, that was a silly mistake. I hope nobody else sees that. Anyway, I've tossed out the bad commits and done it properly this time around.

**Comment by drashna** [comment]
Fantastic!  Can confirm that this fixes the issue I had. :)

**Comment by vomindoraan** [comment]
Rebased this onto the latest master. @jackhumbert If it's not too much of a bother, could you review and merge this soon?

**Comment by drashna** [comment]
Okay, that's a weird effect.... 
it's clearing mods on modded keys, like KC_AT (@) when switching layers. But not the normal key (KC_2). 

Not sure of that's by design, or a coincidence. 

(also found a bug with layer keys and OSM, that's unrelated to this, as I tested on "pre changes").

**Comment by vomindoraan** [comment]
@drashna It should do that even without these changes though, right? Because I reduced the amount of things that are being cleared, not increased it. In any case, I'll look into it later today.

**Comment by drashna** [comment]
Nope.  Without this code change, it releases both.  With this, it releases *just* the mod.

**Comment by vomindoraan** [comment]
Alright, @drashna and I spoke about this on Discord yesterday, and I believe that, for now, this should be merged as-is, just to get the feature out to people (two people asked about it today).

The issue with shifted characters can be temporarily fixed by checking if any of those keys are pressed and manually clearing them, but doing that is very hacky and I'm against it. The proper way to fix it would be to expand the Prevent Stuck Modifiers implementation to store the state of weak mods in addition to keys and real mods.
But I think that should be left for a separate PR. For now, almost none of the keys being cleared is certainly better than _all_ of them being cleared.

**Comment by juaninamill** [comment]
I would like this be merged as-is. Gaming is getting annoying.

**Comment by drashna** [comment]
Figured out the issue I had.  It's the weak mods.  If you clear that, it causes the issue, but if you comment it out....  100% as expected.

```
###########################################
                      ^ released here
```

File: tmk_core/common/action.c [hunk 1]
```diff
@@ -886,10 +886,19 @@ void clear_keyboard(void)
...
+    clear_keyboard_but_mods_and_keys();
+}
+
+/** \brief Utilities for actions. (FIXME: Needs better description)
+ *
+ * FIXME: Needs documentation.
+ */
+void clear_keyboard_but_mods_and_keys()
 {
     clear_weak_mods();
```
Comment (drashna) [inline tmk_core/common/action.c]: Maybe we should add: 
```suggestion
#ifndef STRICT_MOD_LAYER_RELEASE
    clear_weak_mods();
#endif
```

Or even just remove it:
```suggestion
```

**Comment by vomindoraan** [comment]
Yeah, as I mentioned in the above comment, the proper solution to the issue would be to store the state of weak mods in addition to keys and real mods (which is what the PSM implementation does). However, I feel that's beyond the scope of this PR.

File: tmk_core/common/action.c (hunk 1 above)
Comment (drashna) [reply tmk_core/common/action.c]: Looking at the code, I don't think there is a risk here.  

It appears that weak mods are only used by: 
* Modifier'ed keys
* Mod Tap
* Tap Dance

Everything else uses real mods. 

Additionally, I found a bug/unexpected behavior (L203 of action.c).  It clears all weak mods, instead of just releasing just the correct one.  Not sure how to fix that though.

Comment (drashna) [reply tmk_core/common/action.c]: Also, since `clear_keyboard_but_mods_and_keys` is only used a couple of places, we could a a bool to it's parameters, and then clear the mods based on that.

(mostly just spitballing here)

**Comment by micke** [comment]
@vomindoraan Lol, i've been patching qmk myself for a long time now to stop keys being released.
I __just now__ sat down to prepare a proper PR making this configurable to get this into master.
Noticed i got a merge conflict and to my relief you had just done all the work so i don't have to. So thanks! @vomindoraan

And thank you @mechmerlin.

**Comment by vomindoraan** [comment]
Thanks guys! 🎉

**Comment by Maartenwut** [comment]
So happy that this has finally been added - makes my <60% experience much better! Thanks guys 👍

**Comment by PharGone** [comment]
I don't have any idea how to use QMK from scratch, how can I do this using kbfirmware? Is it possible yet?

**Comment by drashna** [comment]
@PharGone 

https://docs.qmk.fm/#/newbs

https://docs.qmk.fm/#/hand_wire?id=getting-some-basic-firmware-set-up

And @mechmerlin just released a nice video showing how he added support for a keyboard, which should cover everything you need to know about supporting a board from scratch. 

https://www.youtube.com/watch?v=fxn5ud4YGeE
