### PR TITLE
LED config fixes

### LINKED ISSUE #17105: [Bug] Various keyboards contain invalid led config
## Describe the Bug

With the recently introduced data driven led config, the crude validation has flagged the following keyboards;
```
⚠ boardsource/lulu: led_config: lulu.c: OOB within g_led_config matrix data
    70 leds
    OOB - led[70] used in config
⚠ boardsource/beiwagon: led_config: beiwagon.c: Unable to parse g_led_config position data
    22 leds
    18 flags
    12 led position
⚠ ryanskidmore/rskeys100: led_config: rskeys100.c: OOB within g_led_config matrix data
    103 leds
    OOB - led[117] used in config
⚠ latincompass/latinpad: led_config: latinpad.c: OOB within g_led_config matrix data
⚠ melgeek/mj64/rev1: led_config: rev1.c: OOB within g_led_config matrix data
⚠ machkeyboards/mach3: led_config: mach3.c: OOB within g_led_config matrix data

⚠ kbdfans/odin/rgb: led_config: rgb.c: Unable to parse g_led_config position data
    MATHS
    missing position data for 7 leds
⚠ keybee/keybee65: led_config: keybee65.c: Unable to parse g_led_config position data
    missing position data for 19 leds
⚠ mechlovin/hannah60rgb/rev2: led_config: rev2.c: Unable to parse g_led_config position data
    missing position data for 5/8 leds
⚠ handwired/hnah108: led_config: hnah108.c: Unable to parse g_led_config position data
    missing position data for 3/1 leds
⚠ linworks/fave84h: led_config: fave84h.c: Unable to parse g_led_config position data
    missing position data for underglow leds
⚠ linworks/fave87h: led_config: fave87h.c: Unable to parse g_led_config position data
    missing position data for underglow leds
```

Also, various keyboards contain content that makes it difficult to parse;
```
MATH
⚠ xelus/dawn60/rev1_qmk: led_config: rev1_qmk.c: Unable to parse g_led_config matrix data
⚠ xelus/pachi/rgb/rev1: led_config: rev1.c: Unable to parse g_led_config matrix data
⚠ xelus/pachi/rgb/rev2: led_config: rev2.c: Unable to parse g_led_config matrix data
⚠ axolstudio/yeti/hotswap: led_config: hotswap.c: Unable to parse g_led_config position data
⚠ handwired/dygma/raise/ansi: led_config: ansi.c: Unable to parse g_led_config matrix data
⚠ handwired/dygma/raise/iso: led_config: iso.c: Unable to parse g_led_config matrix data

MACROS
⚠ system76/launch_1: led_config: launch_1.c: Unable to parse g_led_config matrix data
    LAYOUT
⚠ s_ol/0xc_pad: led_config: 0xc_pad.c: Unable to parse g_led_config matrix data
    LAYOUT + others
⚠ opendeck/32/rev1: led_config: rev1.c: Unable to parse g_led_config position data
    others
⚠ rgbkb/sol/rev2: led_config: rev2.c: Unable to parse g_led_config matrix data
    ifdefs
⚠ rgbkb/pan/rev1/32a: led_config: pan.c: Unable to parse g_led_config position data
    ifdefs
⚠ rgbkb/pan/rev1/proton_c: led_config: pan.c: Unable to parse g_led_config position data
    ifdefs
```

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

```
⚠ handwired/hnah108: led_config: hnah108.c: Unable to parse g_led_config position data
```
Missing a column of LEDs, and LED count was incorrect. Confirmed with video of PCB on Mechlovin Youtube channel.
```
⚠ kbdfans/odin/rgb: led_config: rgb.c: Unable to parse g_led_config position data
```
Removed math expressions and corrected LED count (PCB appears to have 100 keys + 4 logo).
```
⚠ keybee/keybee65: led_config: keybee65.c: Unable to parse g_led_config position data
```
Last row seemed to be missing most of the LEDs. No position info available for underglow LEDs, so they were removed for now. 
```
⚠ linworks/fave84h: led_config: fave84h.c: Unable to parse g_led_config position data
```
No position info available for underglow LEDs, so they were removed for now.
```
⚠ linworks/fave87h: led_config: fave87h.c: Unable to parse g_led_config position data
```
No position info available for underglow LEDs, so they were removed for now.
```
⚠ mechlovin/hannah60rgb/rev2: led_config: rev2.c: Unable to parse g_led_config position data
```
Added flags and positions (at 0,0) for 8 underglow LEDs.
```
⚠ melgeek/mj64/rev1: led_config: rev1.c: OOB within g_led_config matrix data
```
Added missing flags.
```
⚠ opendeck/32/rev1: led_config: rev1.c: Unable to parse g_led_config position data
```
Removed macro for calculating positions. Also fixed a missing ).
```
⚠ ryanskidmore/rskeys100: led_config: rskeys100.c: OOB within g_led_config matrix data
```
No design files available; renumbered LED indexes to be contiguous and adjusted LED count.
```
⚠ xelus/dawn60/rev1_qmk: led_config: rev1_qmk.c: Unable to parse g_led_config matrix data
```
Removed math expressions.
```
⚠ xelus/pachi/rgb/rev1: led_config: rev1.c: Unable to parse g_led_config matrix data
```
Removed math expressions.
```
⚠ xelus/pachi/rgb/rev2: led_config: rev2.c: Unable to parse g_led_config matrix data
```
Removed math expressions.

cc @Xelus22 @ryanskidmore @vuhopkep @ToastyStoemp @mechlovin @melgeek001365 @cmdremily

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #17105

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fauxpark** [comment]
CI failures unrelated.

**Review by ryanskidmore — APPROVED** [review]
lgtm for `ryanskidmore/rskeys100`

**Comment by fauxpark** [comment]
@ryanskidmore and others, would appreciate if you could test these changes, as I don't have any of these boards and in some cases had to make some (not so) educated guesses.

**Review by zvecr — APPROVED** [review]

**Comment by Xelus22** [comment]
LGTM. for my ones. FWIW i made them like that so its easier to calculate the index from row/col.

**Review by Xelus22 — APPROVED** [review]

File: keyboards/opendeck/32/rev1/rev1.c [hunk 1]
```diff
@@ -63,27 +63,28 @@ const is31_led PROGMEM g_is31_leds[RGB_MATRIX_LED_COUNT] = {
     // clang-format on
 };
 
-#define P(x,y) {(x*224 / (MATRIX_COLS - 1)), (y*64 / (MATRIX_ROWS - 1))}
```
Comment (cmdremily) [inline keyboards/opendeck/32/rev1/rev1.c:66]: Please don't do this. It breaks configurability by hard coding in the matrix size, meaning that porting to different sizes of the grid becomes annoying.

**Review by cmdremily — CHANGES_REQUESTED** [review]

File: keyboards/opendeck/32/rev1/rev1.c (hunk 1 above)
Comment (fauxpark) [reply keyboards/opendeck/32/rev1/rev1.c:66]: The problem here is that the CLI can't understand the values in g_led_config when they use macros, and changing the CLI to evaluate them would introduce far too much complexity, and breaks the two-way data-driven mapping.

Comment (cmdremily) [reply keyboards/opendeck/32/rev1/rev1.c:66]: Can't the CLI just run CPP (the C Pre Processor) first and then run on the output of that?

Comment (zvecr) [reply keyboards/opendeck/32/rev1/rev1.c:66]: That was attempted in the work that added `info.json` support, but it was non trivial due to the variables introduced in the build process. Support for parsing `.c` files is not intended long term, and was introduced as mostly a "best effort" to aid the migration process. Instead **all** config will eventually be the `info.json` format, which right now is still intended to be just numeric values. At a point in the future, this will become mandatory for all keyboards in the repo, and those added in PRs.

Comment (cmdremily) [reply keyboards/opendeck/32/rev1/rev1.c:66]: I'm not familiar with the format of the `info.json` file, but I imagine that adding a optional rational x and y scale factors to the `info.json` and multiplying that out in the parsing should be doable. That way the macro here could be removed, leaving the indexes as is and adding the scale factor in the `info.json`.

I don't know fully what the rollout plan of this is, nor do I have the time to get into it. But my spidey sense is tingling here and I get the feeling that this PR is premature. Can the `info.json` format be completed first (hopefully with the above feature) and then the boards migrated directly to that format without this intermediate step that breaks configurability and adds maintenance pain?

Comment (zvecr) [reply keyboards/opendeck/32/rev1/rev1.c:66]: To us, keeping this code in as is, is maintenance pain. Its causing issue in the short term. Extensions to the `info.json` format can happen if someone puts the work in, but that unlikely to be a blocker on this PR getting merged "as is".

**Review by tzarc — APPROVED** [review]

File: keyboards/opendeck/32/rev1/rev1.c (hunk 1 above)
Comment (tzarc) [reply keyboards/opendeck/32/rev1/rev1.c:66]: Data-driven is the way to go at this point -- as @zvecr said we'll welcome future PRs to simplify the definitions, but for now the intended direction is to move away from specifying them in code.

If we look at all the places that may be considered "premature" then we'd have no progress until we "big bang" everything at once, generating even more friction. We've chosen to chip away and iterate over time as a long-term mitigation strategy instead.

Comment (cmdremily) [reply keyboards/opendeck/32/rev1/rev1.c:66]: I realize running a large projects with many contributors is hard. But I disagree with how heavyhandedly this was handled so no need to bother CCing me on future PRs, if you're just going to ignore the comments and go ahead with your change anyway, I'd rather not waste my time.

I also do not accept that features of my project are broken and maintenance burden is applied unilaterally. The code is now yours to maintain.

Comment (fauxpark) [reply keyboards/opendeck/32/rev1/rev1.c:66]: I have to say I don't really understand the benefit of using a macro here. If you want to reuse it for multiple boards with varying layouts (say, an 8x8 version)... you still have to edit the `g_led_config` to add the extra LED indexes/positions/flags anyway.

Additionally, and perhaps more importantly, this specific section of `g_led_config` is *not supposed to be tied to the electrical matrix dimensions*. It's purely for assigning physical X/Y positions to each LED (which may or may not even be associated with a key, as you can flag LEDs as underglow only or even indicator only).

So while this solution works for your particular case, a simple ortholinear layout with a matrix that matches it, and only per-key LEDs, it doesn't necessarily work for every other board.
