### PR TITLE
Improve test invocation, fix Retro Shift bugs, and add Auto+Retro Shift test cases

### LINKED ISSUE #15458: [Bug] Retro Shift not working on Mod Tap keys
## Describe the Bug

Using Retro_Shift has no effect on my Mod Tap keys.
Auto Shift is enabled and works for normal alpha keys.
But when exceeding the `AUTO_SHIFT_TIMEOUT` on the Mod Tap keys without pressing an additional key, retro shift doesn't trigger.

## System Information

 - Keyboard:  Planck
   - Revision (if applicable):  rev6_drop
 - Operating system: macOS 12.1
 - AVR GCC version: 8.4.0
 - ARM GCC version: 8.3.1
 - QMK Firmware version: 0.15.6
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [x] Karabiner
   - [ ] Other:

## Additional Context

Retro Shift added in https://github.com/qmk/qmk_firmware/commit/d9393b86842b7ef143259b5f771ae7969f98cbb4

Relevant part of `config.h`:
```
// Tapping Term
#define TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY

// Prevent normal rollover on alphas from accidentally triggering mods.
#define IGNORE_MOD_TAP_INTERRUPT

// Auto Shift
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_SPECIAL
#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
#define AUTO_SHIFT_NO_SETUP
#define RETRO_SHIFT
```

### PR DESCRIPTION
**Pull request by IsaacElenbaas**
## Description

This PR:
* Fixes all of the Retro Shift bugs I have run into or been alerted to in the past couple of months
* Includes some small Retro Shift doc additions/fixes
* Adds test cases for Auto and Retro Shift
* Includes test invocation improvements:
  * Running `make test:auto_shift` will run all Auto Shift tests
  * Running `make test:auto_shift:retro_shift:permissive_hold` (or similar) allows running tests in different directories that have the same name, versus the old behavior of whichever's parent directory was later in the alphabet
  * Running `make test:permissive_hold` will run both Retro Shift's `permissive_hold` test and the normal one

It also makes `RETRO_SHIFT` not default to `TAPPING_TERM`, as the behavior can be confusing (trying out the feature -> holding -> not releasing between `AUTO_SHIFT_TIMEOUT` and `TAPPING_TERM` which are probably close for most users). The old behavior also made it impossible to make holds of any length send the shifted value aside from setting `RETRO_SHIFT` to `INT_MAX` or something.

## Types of Changes

- [X] Core
- [X] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* #15458
* Made Retro Shift respect `DYNAMIC_TAPPING_TERM`
* Miscellaneous Retro Shift issues that do not have issues
* Updated out-of-date default function in docs

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/process_keycode/process_auto_shift.c [hunk 1]
```diff
@@ -178,7 +178,11 @@ static bool autoshift_press(uint16_t keycode, uint16_t now, keyrecord_t *record)
 #        ifdef TAPPING_TERM_PER_KEY
         get_tapping_term(autoshift_lastkey, record)
 #        else
+#            ifdef DYNAMIC_TAPPING_TERM_ENABLE
+        g_tapping_term
+#            else
         TAPPING_TERM
+#            endif
```
Comment (precondition) [inline quantum/process_keycode/process_auto_shift.c:185]:
```suggestion
        g_tapping_term
```
The variable `g_tapping_term` is not behind any `#ifdef` (other than `#ifndef NO_ACTION_TAPPING`) so even if `DYNAMIC_TAPPING_TERM_ENABLE` is off, `g_tapping_term` is still a reference to the `TAPPING_TERM` defined by the user (or 200 by default);

File: quantum/action_tapping.c [hunk 2]
```diff
@@ -126,7 +126,7 @@ bool process_tapping(keyrecord_t *keyp) {
 #        ifdef RETRO_TAPPING_PER_KEY
                 get_retro_tapping(tapping_keycode, keyp) &&
 #        endif
-                (RETRO_SHIFT + 0) != 0 && TIMER_DIFF_16(event.time, tapping_key.event.time) < (RETRO_SHIFT + 0)
+                ((RETRO_SHIFT + 0) == 0 || TIMER_DIFF_16(event.time, tapping_key.event.time) < (RETRO_SHIFT + 0))
```
Comment (precondition) [inline quantum/action_tapping.c:129]:
```suggestion
                // if RETRO_SHIFT is not defined with an explicit value (`#define RETRO_SHIFT`) OR
                // the time that separates this key event from the tapping key event is below the retro shift term defined by the user (`#define RETRO_SHIFT <value>`)
                ((RETRO_SHIFT + 0) == 0 || TIMER_DIFF_16(event.time, tapping_key.event.time) < (RETRO_SHIFT + 0))
```
It isn't immediately obvious what this line means so adding a comment can help future readers from asking themselves the same question as me regarding the `+ 0`.

Although, I'm worried that the wording "the time that separates *this key event* from the *tapping key event*" may mislead some readers into thinking that `keyp` (from which `event` is derived) is necessarily a different key from `tapping_key`.

File: quantum/action_tapping.c [hunk 3]
```diff
@@ -362,7 +362,7 @@ bool process_tapping(keyrecord_t *keyp) {
...
```
Comment (precondition) [inline quantum/action_tapping.c:365]:
```suggestion
                // if RETRO_SHIFT is not defined with an explicit value (`#define RETRO_SHIFT`) OR
                // the time that separates this key event from the tapping key event is below the retro shift term defined by the user (`#define RETRO_SHIFT <value>`)
                ((RETRO_SHIFT + 0) == 0 || TIMER_DIFF_16(event.time, tapping_key.event.time) < (RETRO_SHIFT + 0))
```
A second comment saying the same thing on the same line of code might not be very helpful but in my opinion, it doesn't hurt to repeat it.

**Review by precondition — CHANGES_REQUESTED** [review]

File: quantum/action_tapping.c (hunk 2 above)
Comment (IsaacElenbaas) [reply quantum/action_tapping.c:136]: Is that good? Not trying to explain what variables or events are in this scenario makes the most sense to me, this section just makes the `if`s with a `WITHIN_TAPPING_TERM` check also reference `RETRO_SHIFT` and this points that out.

Comment (precondition) [reply quantum/action_tapping.c:136]: I would delete the two last comment lines. "[T]his [...] eliminates the hold action for use with the mouse" is kind of saying the opposite of what you mean.

**Comment by IsaacElenbaas** [comment]
`get_hold_on_other_key_press` isn't exposed, last push added it to `action_tapping.h`.

**Comment by IsaacElenbaas** [comment]
Last commit made `record->event.pressed` not `false` where there was no good reason for it to be. Not sure what I was thinking when I did that one.

**Review by drashna — APPROVED** [review]

**Comment by tzarc** [comment]
Conflicts once base branch swapped to `develop`.

**Comment by IsaacElenbaas** [comment]
Conflict fixed.

**Comment by IsaacElenbaas** [comment]
Last commit fixed having `IGNORE_MOD_TAP_INTERRUPT` set and rolling starting from a Retro Shifted key not allowing the Retro Shifted key to be shifted.

**Comment by IsaacElenbaas** [comment]
Since this hasn't been merged yet I'm adding unit tests. Shouldn't be long at all but don't review/merge in the meantime.

**Comment by IsaacElenbaas** [comment]
Conflicts with #15741 now but that's just because I found things that could be deleted so should be easy :)

I had to make some changes to the way tests are run to allow Retro Shift and the Tap Hold configurations to have the same folder names and both be runnable. I think the glob-like behavior is pretty good, if we name things appropriately one can run relevant test cases easily and without doing them all during development. It also sort of mirrors the keyboard commands and generated files.

I need to look into the failing combo tests, give this actual physical board testing, and check if I've managed to fix one last bug unintentionally or if it needs a workaround, but there shouldn't be many changes what with the tests passing.

File: quantum/action_tapping.c [hunk 4]
```diff
@@ -504,8 +483,28 @@ void waiting_buffer_scan_tap(void) {
...
+#    if (defined(AUTO_SHIFT_ENABLE) && defined(RETRO_SHIFT))
+    uint16_t tapping_keycode = get_record_keycode(&tapping_key, false);
+#    endif
     for (uint8_t i = waiting_buffer_tail; i != waiting_buffer_head; i = (i + 1) % WAITING_BUFFER_SIZE) {
-        if (IS_TAPPING_KEY(waiting_buffer[i].event.key) && !waiting_buffer[i].event.pressed && WITHIN_TAPPING_TERM(waiting_buffer[i].event)) {
+        // clang-format off
+        if (IS_TAPPING_KEY(waiting_buffer[i].event.key) && !waiting_buffer[i].event.pressed && (
+            WITHIN_TAPPING_TERM(waiting_buffer[i].event)
+#    if defined(AUTO_SHIFT_ENABLE) && defined(RETRO_SHIFT)
+            || (
```
Comment (IsaacElenbaas) [inline quantum/action_tapping.c:494]: This being missing made so much weird behavior and caused 2-3 months of on-and-off playing with one bug and then getting frustrated and quitting for a while.

File: quantum/action.c [hunk 5]
```diff
@@ -1099,6 +1099,10 @@ bool is_tap_key(keypos_t key) {
  * FIXME: Needs documentation.
  */
 bool is_tap_record(keyrecord_t *record) {
+    // layer_switch_get_action would attempt to read OOB for TICKs
+    if (IS_NOEVENT(record->event)) {
```
Comment (IsaacElenbaas) [inline quantum/action.c:1103]: May not be necessary anymore if action_tapping isn't led into the sequence of branches that triggered it after more fixes, but it is definitely possible.

File: tests/auto_shift/retro_shift/default_mod_tap/no_timeout/test.mk [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# --------------------------------------------------------------------------------
+# Keep this file, even if it is empty, as a marker that this folder contains tests
+# --------------------------------------------------------------------------------
+
+AUTO_SHIFT_ENABLE = yes
```
Comment (IsaacElenbaas) [inline tests/auto_shift/retro_shift/default_mod_tap/no_timeout/test.mk:20]: Not sure how only some of these ended up without a trailing newline, will fix in the push with combo tests.

**Comment by IsaacElenbaas** [comment]
Resolved conflicts and removed duplicate #18063

**Comment by tzarc** [comment]
Conflicts fixed, kicked off CI.

**Comment by IsaacElenbaas** [comment]
Thanks, I had stopped checking for conflicts on this as often.

If this is being eyed for this cycle, there was never any discussion here about how this changes how tests can be invoked (see description) or review of those changes. It only adds functionality, but I just wanted to note that.

**Comment by IsaacElenbaas** [comment]
Will get around to fixing those sometime but this month will be busy (maybe spring break). Shouldn't be bad but IGNORE_MOD_TAP_INTERRUPT by default was merged so there will be some non-obvious conflicts and it will need re-testing.

**Comment by precondition** [comment]
> Will get around to fixing those sometime but this month will be busy (maybe spring break). Shouldn't be bad but IGNORE_MOD_TAP_INTERRUPT by default was merged so there will be some non-obvious conflicts and it will need re-testing.

The PR you refer to has been severely changed and greatly reduced in scope. The global `IGNORE_MOD_TAP_INTERRUPT` still exists and the default behavior of mod-taps has not been changed. The only notable change is that `IGNORE_MOD_TAP_INTERRUPT_PER_KEY`/`bool get_ignore_mod_tap_interrupt` no longer exists and is superseded by `bool get_hold_on_other_key_press`.

**Comment by IsaacElenbaas** [comment]
Yeah, I actually didn't run into any conflicts from it. The unnecessary conditions have been removed so if this is merged before the PR that fully removes IMTI there hopefully shouldn't be much if anything to do for Retro Shift other than swap the IMTI and default test cases.

Most conflicts were from #17282, thanks a lot for that cleanup @fxkuehl. `action_tapping.c` is hard to wrap your head around on its own and I made it a good deal worse, it is much better now.
Unless someone thinks otherwise I'm holding off on removing the now unused `TAP_IS_LT/MT/RETRO` as they are small and may still be useful later. Swapping times to let the existing logic work instead of doing things manually worked, but the [MT vs LT behavior differences](https://cdn.discordapp.com/attachments/451392568345755648/747388373781708930/tap-holds-qmk.pdf) may need to be accounted for in Retro Shift or some other feature in the future (not that I have any clue how many of them are intentional/documented and *should* be accounted for).

All tests are still passing and didn't need adjustments, got this flashed on my main board and everything seems the same as well. Should be ready for review/merge IMO. Note that the test invocation changes still haven't had any discussion, though again they only add functionality and old commands to run tests still work.

**Comment by IsaacElenbaas** [comment]
Resolved (not pushed) conflicts with #15847 which weren't too bad, tests are failing now. Other tests and mine are getting a lot more empty reports and mine are getting wrong keys, definitely looks like some stuff in that could be the cause. At a *very* brief glance, I don't see why moving the `IS_EVENT` checks like that did in `action_tapping.c` should still work.

Will look into deeper soon:tm:

File: quantum/action.c [hunk 7]
```diff
@@ -497,7 +497,7 @@ void process_action(keyrecord_t *record, action_t action) {
                 default:
                     if (event.pressed) {
                         if (tap_count > 0) {
-#    ifdef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
+#    ifdef HOLD_ON_OTHER_KEY_PRESS
```
Comment (IsaacElenbaas) [inline quantum/action.c:500]: Life got crazy but I finally got around to looking at this again after stale-bot reminded me. Should be good to go again, other combo tests are failing right now so the action won't run but they're passing.

The issues weren't actually from that PR, they were from a couple of the things I had thrown in in the last PR to make Retro Shift ready for `HOLD_ON_OTHER_KEY_PRESS` before it happened not being quite correct. I also fixed the above, which I think wasn't noticed in the three months since the switch because an earlier evaluation was also added (which I had to exclude Retro Shift from).

**Review by drashna — APPROVED** [review]

**Review by tzarc — APPROVED** [review]
