### PR TITLE
Fix RESET not working for keyboards with Kiibohd bootloader

### LINKED ISSUE #6112: WhiteFox - RESET goes to "Kiibohd DFU Secure", cannot flash - needs to enter "Kiibohd DFU"
## Describe the Bug
When using the RESET keycode in QMK firmware, the WhiteFox enters "Kiibohd DFU Secure" (as seen via dfu-util --list). In this state, it appears it cannot be flashed - dfu-util reports an error trying to copy data to the MCU. When using the reset button on the back of the keyboard, it enters "Kiibohd DFU" and is able to be flashed. See "Additional Context" section for output of dfu-util list and download commands in the two modes.

Essentially, the RESET keycode isn't useful for the WhiteFox (and presumably other boards using the Kiibohd bootloader). 

## System Information

 - Keyboard:  WhiteFox
   - Revision (if applicable):  True Fox
 - Operating system: Ubuntu 18.04
 - AVR GCC version: avr-gcc (GCC) 5.4.0

 - ARM GCC version: arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620

 - QMK Firmware version: 0.6.398

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

#### Using QMK RESET keycode (flash fails):
$ sudo dfu-util --list
dfu-util 0.9
Found DFU: [1c11:b007] ver=0295, devnum=89, cfg=1, intf=0, path="1-5", alt=0, name="_**Kiibohd DFU Secure**_", serial="85C100007DEB00150007001032194E45 - mk20dx256vlh7"

$ sudo dfu-util -D .build/whitefox_imchipwood.bin 
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 1c11
Match product ID from file: b007
Opening DFU capable USB device...
ID 1c11:b007
Run-time device DFU version 0101
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0101
Device returned transfer size 1024
Copying data from PC to DFU device
Download        [                         ]   0%            0 bytes
_**dfu-util: Error during download**_

#### Using reset button on back of keyboard (flash successful):
$ sudo dfu-util --list
dfu-util 0.9
Found DFU: [1c11:b007] ver=0295, devnum=91, cfg=1, intf=0, path="1-5", alt=0, name="_**Kiibohd DFU**_", serial="85C100007DEB00150007001032194E45 - mk20dx256vlh7"

$ sudo dfu-util -D .build/whitefox_imchipwood.bin 
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 1c11
Match product ID from file: b007
Opening DFU capable USB device...
ID 1c11:b007
Run-time device DFU version 0101
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0101
Device returned transfer size 1024
Copying data from PC to DFU device
Download        [=========================] 100%        37440 bytes
Download done.
state(7) = dfuMANIFEST, status(0) = No error condition is present
state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Done!

### PR DESCRIPTION
**Pull request by Andrew-Fahmy**
This is a fix for https://github.com/qmk/qmk_firmware/issues/6112. Keyboards with the Kiibohd bootloader would go into [secure DFU mode](https://github.com/kiibohd/controller/blob/master/Bootloader/Documentation/SecureDFU.md). In secure DFU mode the bootloader would do an extra key verification where it would look for a key in the first block of the new firmware. There is a way to disable this functionality, and after talking with @haata, I was able to implement this fix.

I have a K-type and this fixed the issue on my keyboard. If anyone that has a different keyboard, let me know if this fix also works on your board.

## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* Fixes #6112

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: platforms/chibios/bootloader.c [hunk 1]
```diff
@@ -123,10 +123,16 @@ void enter_bootloader_mode_if_requested(void) { /* Jumping to bootloader is not
 #    if defined(BOOTLOADER_KIIBOHD)
 /* Kiibohd Bootloader (MCHCK and Infinity KB) */
 #        define SCB_AIRCR_VECTKEY_WRITEMAGIC 0x05FA0000
+
+// taken from Kiibohd/controller
+#        define VBAT_SECURE1            *(volatile uint32_t *)0x4003E018 // Kiibohd Secure 32 bit register 1 (24th byte)
+#        define VBAT_SECURE2            *(volatile uint32_t *)0x4003E01C // Kiibohd Secure 32 bit register 2 (28th byte)
```
Comment (fauxpark) [inline platforms/chibios/bootloader.c:129]:
```suggestion
```

File: platforms/chibios/bootloader.c [hunk 2]
```diff
@@ -123,10 +123,16 @@ void enter_bootloader_mode_if_requested(void) { /* Jumping to bootloader is not
...
 const uint8_t              sys_reset_to_loader_magic[] = "\xff\x00\x7fRESET TO LOADER\x7f\x00\xff";
 __attribute__((weak)) void bootloader_jump(void) {
     void *volatile vbat = (void *)VBAT;
     __builtin_memcpy(vbat, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
+    VBAT_SECURE1 = 0;
+    VBAT_SECURE2 = 0;
```
Comment (fauxpark) [inline platforms/chibios/bootloader.c:135]:
```suggestion
```

File: platforms/chibios/bootloader.c [hunk 3]
```diff
@@ -123,10 +123,16 @@ void enter_bootloader_mode_if_requested(void) { /* Jumping to bootloader is not
 #    if defined(BOOTLOADER_KIIBOHD)
 /* Kiibohd Bootloader (MCHCK and Infinity KB) */
 #        define SCB_AIRCR_VECTKEY_WRITEMAGIC 0x05FA0000
+
+// taken from Kiibohd/controller
+#        define VBAT_SECURE1            *(volatile uint32_t *)0x4003E018 // Kiibohd Secure 32 bit register 1 (24th byte)
+#        define VBAT_SECURE2            *(volatile uint32_t *)0x4003E01C // Kiibohd Secure 32 bit register 2 (28th byte)
 const uint8_t              sys_reset_to_loader_magic[] = "\xff\x00\x7fRESET TO LOADER\x7f\x00\xff";
```
Comment (fauxpark) [inline platforms/chibios/bootloader.c:130]:
```suggestion
const uint8_t              sys_reset_to_loader_magic[] = "\xFF\x00\x7FRESET TO LOADER\x7F\x00\xFF\x00\x00\x00\x00\x00\x00\x00\x00";
```

**Review by fauxpark — CHANGES_REQUESTED** [review]
If I understand this correctly, the change can be simplified as the current code is already modifying the VBAT register.

File: platforms/chibios/bootloader.c (hunk 3 above)
Comment (fauxpark) [reply platforms/chibios/bootloader.c:130]: If this doesn't work, it might need three more `\x00`s on the end to fill out the 32 bytes.

Comment (Andrew-Fahmy) [reply platforms/chibios/bootloader.c]: I added enough to fill out 31 bytes, and with the string terminator it is 32 bytes. Anything less or more doesn't work.

**Comment by Andrew-Fahmy** [comment]
That's definitely a cleaner way of doing it, thanks for the suggestion!

**Review by fauxpark — APPROVED** [review]

**Review by zvecr — APPROVED** [review]
