### PR TITLE
 Fix functions layer_debug and default_layer_debug

### LINKED ISSUE #25911: [Bug] debug function void layer_debug(void) and void default_layer_debug(void) not working
### Describe the Bug

I am playing with quantum/action.c and quantum/action_layer.c to better understand the layer system.

I have used debug (qmk console), where it prints some interesting stuff: 
```
Keychron:Keychron Q1v1:1: ---- action_exec: start -----
Keychron:Keychron Q1v1:1: EVENT: 050Bu(12676)
Keychron:Keychron Q1v1:1: ACTION: ACT_LAYER_TAP[3:F1] layer_state:  default_layer_state: 
Keychron:Keychron Q1v1:1: layer_state:  to 
Keychron:Keychron Q1v1:1: processed: 050Bu(12676):0 

```
I was surprised by the missing information "layer_state:  to ". The value here, is computed by the following function: 

```
/** \brief Layer debug printing
 *  
 * Print out the hex value of the 32-bit layer state, as well as the value of the highest bit.
 */ 
void layer_debug(void) {
    ac_dprintf("%08hX(%u)", layer_state, get_highest_layer(layer_state));
}   
```
I have noticed that if I remove the 'h' of the print, I get a more interesting information:
`ac_dprintf("%08X(%u)", layer_state, get_highest_layer(layer_state));` :

```
Keychron:Keychron Q1v1:1: ---- action_exec: start -----
Keychron:Keychron Q1v1:1: EVENT: 050Bd(62047)
Keychron:Keychron Q1v1:1: ACTION: ACT_LAYER_TAP[3:F1] layer_state: 00000000(0) default_layer_state: 00000004(2)
Keychron:Keychron Q1v1:1: layer_state: 00000000(0) to 00000008(3)
Keychron:Keychron Q1v1:1: processed: 050Bd(62047):0 
```
I don't know if anyone can correct this (or if you would prefer me to make a merge request.

### Keyboard Used

keychron/q1v1/iso

### Link to product page (if applicable)

_No response_

### Operating System

Linux

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.2.0
Ψ QMK home: /home/pierre/qmk_firmware
Ψ Detected Linux (Fedora Linux 43 (Xfce)).
Ψ Userspace enabled: False
Ψ Git branch: master
Ψ Repo version: 0.30.12
⚠ Git has unstashed/uncommitted changes.
Ψ - Latest master: 2025-12-25 17:03:53 +0100 (0b182f3abf) -- Add MAC layout (colors not fully workings).
Ψ - Latest upstream/master: 2025-12-25 00:24:50 +0000 (acbeec29da) -- Reduce frequency of automatic workflow run approval (#25896)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2025-11-21 02:13:14 +0000 (81cc69c2dd) -- Bump actions/checkout from 5 to 6 (#25807)
Ψ - Common ancestor with upstream/develop: None
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 15.2.0
Ψ Successfully compiled using arm-none-eabi-gcc
Ψ Successfully tested arm-none-eabi-binutils using arm-none-eabi-size
Ψ Found avr-gcc version 15.2.0
Ψ Successfully compiled using avr-gcc
Ψ Successfully tested avr-binutils using avr-size
Ψ Found avrdude version t
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11-dev
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2025-05-15 08:25:11 +0000 --  (8bd61b8043)
Ψ - lib/chibios-contrib: 2025-01-08 21:03:31 +0100 --  (3ac181e4)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2025-04-20 21:24:29 +1000 --  (d0c5cac)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Piervit**
Correct display of the debug functions 'layer_debug' and 'default_layer_debug'.

## Description

In the file action_layer.c, the debug functions 'layer_debug' and 'default_layer_debug' where not properly displaying the layer (used an unsigned short int instead of a 32 bit unsigned int). 

The issue is described in the associated issue: [https://github.com/qmk/qmk_firmware/issues/25911](https://github.com/qmk/qmk_firmware/issues/25911)

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #25911

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/action_layer.c [hunk 1]
```diff
@@ -60,7 +60,7 @@ static void default_layer_state_set(layer_state_t state) {
  * Print out the hex value of the 32-bit default layer state, as well as the value of the highest bit.
  */
 void default_layer_debug(void) {
-    ac_dprintf("%08hX(%u)", default_layer_state, get_highest_layer(default_layer_state));
+    ac_dprintf("%08X(%u)", default_layer_state, get_highest_layer(default_layer_state));
```
Comment (zvecr) [inline quantum/action_layer.c]:
```suggestion
    ac_dprintf("%08lX(%u)", (uint32_t)default_layer_state, get_highest_layer(default_layer_state));
```

File: quantum/action_layer.c [hunk 2]
```diff
@@ -231,7 +231,7 @@ void layer_xor(layer_state_t state) {
  * Print out the hex value of the 32-bit layer state, as well as the value of the highest bit.
  */
 void layer_debug(void) {
-    ac_dprintf("%08hX(%u)", layer_state, get_highest_layer(layer_state));
+    ac_dprintf("%08X(%u)", layer_state, get_highest_layer(layer_state));
```
Comment (zvecr) [inline quantum/action_layer.c]:
```suggestion
    ac_dprintf("%08lX(%u)", (uint32_t)layer_state, get_highest_layer(layer_state));
```

**Review by zvecr — CHANGES_REQUESTED** [review]
Still has issues with `LAYER_STATE_32BIT` on ChibiOS based builds:
```
quantum/action_layer.c:63:16: error: format '%X' expects argument of type 'unsigned int', but argument 2 has type 'layer_state_t' {aka 'long unsigned int'} [-Werror=format=]
   63 |     ac_dprintf("%08X(%u)", default_layer_state, get_highest_layer(default_layer_state));
      |                ^~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            layer_state_t {aka long unsigned int}
quantum/logging/debug.h:60:46: note: in definition of macro 'dprintf'
   60 |             if (debug_config.enable) xprintf(fmt, ##__VA_ARGS__); \
      |                                              ^~~
quantum/action_layer.c:63:5: note: in expansion of macro 'ac_dprintf'
   63 |     ac_dprintf("%08X(%u)", default_layer_state, get_highest_layer(default_layer_state));
      |     ^~~~~~~~~~
quantum/action_layer.c:63:20: note: format string is defined here
   63 |     ac_dprintf("%08X(%u)", default_layer_state, get_highest_layer(default_layer_state));
      |                 ~~~^
      |                    |
      |                    unsigned int
      |                 %08lX
```

**Comment by Piervit** [comment]
I agree with your change zvecr. I also have tested it on my Keychron Q1 keyboard.

**Review by drashna — APPROVED** [review]

**Comment by Piervit** [comment]
I have seen the changes were approved.
I don't know if something is expected from me now (for exemple to squash in a single commit). I haven't the right to push myself so I expect a maintainer will do it (or notify that I need to do something).
