### PR TITLE
fixed I2C driver support for stm32f4

### LINKED ISSUE #7524: can't compile Chibios I2CV1 driver under stm32f4 through QMK configurator
While I compile the keyboard (matrix/noah), the following error occurs:
image

But the latest qmk  compiled successfully under my local machine, and I can't find " qEvt(0x0000);" on the lib/chibios/os/hal/ports/STM32/LLD/I2Cv1/hal_i2c_lld.c. I also checked chibios 17, 18 and 19, but they all did not contains such codes.

The cannonkeys/ortho48 also use the I2CV1, and it compiled successfully through the qmk configurator.

### PR DESCRIPTION
**Pull request by yulei**
stm32f4 uses I2Cv1 and GPIOv2 drivers, so the current definitions on i2c_master.h should be modified.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #7524 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: drivers/arm/i2c_master.h [hunk 1]
```diff
@@ -27,7 +27,7 @@
 #include "ch.h"
 #include <hal.h>
 
-#if defined(STM32F1XX) || defined(STM32F1xx) || defined(STM32F2xx) || defined(STM32F4xx) || defined(STM32L0xx) || defined(STM32L1xx)
+#if defined(STM32F1XX) || defined(STM32F1xx) || defined(STM32F2xx) || defined(STM32F4xx) || defined(STM32F4XX) || defined(STM32L0xx) || defined(STM32L1xx)
```
Comment (fauxpark) [inline drivers/arm/i2c_master.h]: Some quick grepping reveals that these defines should perhaps all be uppercase - eg. `STM32F1xx` doesn't exist in lib/chibios or chibios-contrib, but `STM32F1XX` does.

Comment (yulei) [reply drivers/arm/i2c_master.h]: yes, but I'm not sure why it was defined as lower cases before. Chibios does not use lower case dfinitions.

File: drivers/arm/i2c_master.h [hunk 2]
```diff
@@ -61,6 +61,10 @@
 #    ifndef I2C1_DUTY_CYCLE
 #        define I2C1_DUTY_CYCLE STD_DUTY_CYCLE /* FAST_DUTY_CYCLE_2 */
 #    endif
+#    ifndef PAL_MODE_STM32_ALTERNATE_OPENDRAIN /* stm32f4 uses GPIOv2 */
+#        define I2C_PAL_MODE 4
```
Comment (zvecr) [inline drivers/arm/i2c_master.h]: This kinda bypasses the `I2C1_SCL_PAL_MODE` stuff, and would prefer it was aligned in a separate `USE_GPIOV1` block like <https://github.com/qmk/qmk_firmware/blob/master/quantum/backlight/backlight_arm.c#L14>

File: drivers/arm/i2c_master.h (hunk 1 above)
Comment (fauxpark) [reply drivers/arm/i2c_master.h]: It probably simply wasn't caught until now, I guess. There are currently no F2, L0 or L1 boards in QMK, so the fact that those defines here don't exist either, has gone unnoticed.

File: drivers/arm/i2c_master.h (hunk 2 above)
Comment (yulei) [reply drivers/arm/i2c_master.h]: the pin mode definitions were changed, and also updated the i2c_master.c for this change.

File: drivers/arm/i2c_master.h (hunk 1 above)
Comment (zvecr) [reply drivers/arm/i2c_master.h]: It was copy-pasted from somewhere, though in the original ticket, it doesnt seem like its in the linked blog https://github.com/qmk/qmk_firmware/pull/6262#issuecomment-508912088

Comment (yulei) [reply drivers/arm/i2c_master.h]: STM32F1xx does not exist in the CMSIS and ST's HAL library. They should come form stm32arduino library.

Comment (zvecr) [reply drivers/arm/i2c_master.h]: Changing the rest of the defines is kinda out of scope for this PR. The new addition is consistent with what ChibiOS, so lets tackle any other change separately.

File: drivers/arm/i2c_master.h [hunk 3]
```diff
@@ -51,6 +51,22 @@
 #    define I2C1_SDA 7
 #endif
 
+#if defined(STM32F4XX) || defined (STM32F3XX)
```
Comment (zvecr) [inline drivers/arm/i2c_master.h]: Only f1 use gpiov1, <https://www.playembedded.org/blog/chibioshal-design-an-object-oriented-approach/#Achieving_abstraction_using_a_layered_architecture_design>, so can this be aligned as per previous suggestions to:
```c
#    if defined(STM32F1XX)
#        define USE_GPIOV1
#    endif
`

Comment (yulei) [reply drivers/arm/i2c_master.h]: updated to the USE_GPIOV1
