### PR TITLE
core: chibios: bootloader: use integer pointers as volatile

### LINKED ISSUE #12925: [Bug] ChibiOS compilation error: '__builtin_memcpy' offset [0, 21] is out of the bounds [0, 0]
I'm not sure whether I should open this issue here, on tmk, or chibios, but it's not in any of the submodules, so I guess I'll start here. If it doesn't belong here, please redirect me to the correct place.

## Describe the Bug

When trying to compile the firmware for ergodox_infinity, I get the following output:

```
$ MAKEFLAGS=-j1 make ergodox_infinity:default MASTER=right

QMK Firmware 0.12.38
Making ergodox_infinity with keymap default

arm-none-eabi-gcc (Arch Repository) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/ergodox_infinity/keymaps/default/keymap.c                                      [OK]
Compiling: quantum/command.c                                                                        [OK]
Compiling: tmk_core/common/chibios/bootloader.c                                                    tmk_core/common/chibios/bootloader.c: In function 'bootloader_jump':
tmk_core/common/chibios/bootloader.c:90:5: error: '__builtin_memcpy' offset [0, 21] is out of the bounds [0, 0] [-Werror=array-bounds]
   90 |     __builtin_memcpy((void *)VBAT, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:417: .build/obj_ergodox_infinity_default/common/chibios/bootloader.o] Error 1
Make finished with errors
make: *** [Makefile:523: ergodox_infinity:default] Error 1
```

This is after a second make run, to reduce the output for files that have already previously been compiled successfully. 

## System Information

 - Keyboard:  Ergodox Infinity
 - Operating system: ArchLinux
 - ARM GCC version: 11.1.0
 - QMK Firmware version: 0.12.38 (I'm currently on commit hash a5d7e83985ae07689cc71ab1dd2755a8ac335df3)
 - Any keyboard related software installed? None

## Additional Context

A few days ago, this compilation ran just fine, and this error happened both before rebasing on the latest master commid and after. My guess is that something changed in my local environment, since running it in the Docker container from the provided Dockerfile, works flawlessly. 

The `arm-none-eabi-gcc` package on archlinux received an update 4 days ago, so I assume that that is the culprit, I'm just not sure why.

I have set up a Dockerfile that reproduces the error (at least at time of writing) using the archlinux base image:

```Dockerfile
FROM archlinux

RUN pacman -Syy \
	&& pacman -S --noconfirm \
		make \
		git \
		diffutils \
		arm-none-eabi-gcc \
		qmk \
	&& git clone https://github.com/qmk/qmk_firmware

WORKDIR /qmk_firmware
RUN git checkout a5d7e83985ae07689cc71ab1dd2755a8ac335df3 \
	&& make git-submodule

CMD make ergodox_infinity:default
```

### PR DESCRIPTION
**Pull request by t-8ch**
## Description

core: chibios: bootloader: use integer pointers as volatile
    
This prevents gcc from incorrectly trying to validate array bounds.
    
```
tmk_core/common/chibios/bootloader.c: error: '__builtin_memcpy' offset [0, 21] is out of the bounds [0, 0] [-Werror=array-bounds]
  107 |     __builtin_memcpy((void *) VBAT, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
    
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578#c16

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #12925 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

Note: This is only compile tested, as I don't have such a device.

### CODE REVIEW

**Comment by tzarc** [comment]
Casting `VBAT` to `(volatile void*)` doesn't work?

File: tmk_core/common/chibios/bootloader.c [hunk 1]
```diff
@@ -103,7 +103,8 @@ void enter_bootloader_mode_if_requested(void) {
 #        define SCB_AIRCR_VECTKEY_WRITEMAGIC 0x05FA0000
 const uint8_t              sys_reset_to_loader_magic[] = "\xff\x00\x7fRESET TO LOADER\x7f\x00\xff";
 __attribute__((weak)) void bootloader_jump(void) {
-    __builtin_memcpy((void *)VBAT, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
```
Comment (tzarc) [inline tmk_core/common/chibios/bootloader.c:106]: Casting `VBAT` to `(volatile void*)` doesn't work?
```c
    __builtin_memcpy((volatile void *)VBAT, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
```

Comment (t-8ch) [reply tmk_core/common/chibios/bootloader.c:106]: No

Comment (t-8ch) [reply tmk_core/common/chibios/bootloader.c:106]: Would need to be `(void *volatile)`, but that also doesn't work.

**Review by tzarc — APPROVED** [review]

File: tmk_core/common/chibios/bootloader.c (hunk 1 above)
Comment (tzarc) [reply tmk_core/common/chibios/bootloader.c:106]: Ah, volatile pointer, not volatile data. Fair enough.

**Review by fauxpark — APPROVED** [review]

**Comment by fauxpark** [comment]
@firetech

**Comment by firetech** [comment]
> @firetech

@fauxpark Eh, hi? 🤔

**Comment by fauxpark** [comment]
Just thought you may want to check this works, as OP doesn't have a Kinetis device :)

**Comment by firetech** [comment]
Ah, read up a bit on #12925. Without that context I was wildly confused...

I haven't had any such issues compiling on my Debian system, though. Maybe we should ping @TheEdgeOfRage to check if it solves their issue? :)

**Comment by fauxpark** [comment]
Whoops, didn't notice the linked issue. Sorry for the noise.

**Comment by firetech** [comment]
No problem, happy to help anyway. 😛

**Comment by firetech** [comment]
I can confirm that the fix doesn't seem to introduce any issues on my Debian system at least. Compiling (still) works fine, and my RESET key does what it should.

**Comment by TheEdgeOfRage** [comment]
For completeness sake, I can confirm that this fixed it for me. Thanks :+1:
