### PR TITLE
Fix debouncing issue for eager algorithms

### LINKED ISSUE #6032: With eager_pk, fast key stroke will give stucked key event
## Describe the Bug
When you select eager_pk as your debouncing filter,
if you press and release a key before the DEBOUNCE period ends,
that key will get stucked and keep appears to be held down to the OS and the user.

## How to Reproduce
rules.mk:
`DEBOUNCE_TYPE=eager_pk`
config.h:
`#define DEBOUNCE 100`
and hit any key real quick.

## Additional Context
The bug is introduced with this commit.
https://github.com/qmk/qmk_firmware/commit/d0fb7005d51be7c876e63e87778d080c8a733a13 https://github.com/qmk/qmk_firmware/pull/5621

Here is an example how to fix this.
https://github.com/elfmimi/qmk_firmware/commit/c69f74025dd1a3e16e2d93f2dbfcb1bcb6ec6978

**Push notice:** @alex-ong

### PR DESCRIPTION
**Pull request by drashna**
## Description

Fixes issue with stuck keys on the Per Key and Per Row debouncing algorithms. 

## Types of Changes

- [x] Core
- [x] Bugfix
## Issues Fixed or Closed by This PR

* Fixes #6032 

## Checklist
- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

File: quantum/debounce/eager_pk.c [hunk 1]
```diff
@@ -88,16 +89,22 @@ void update_debounce_counters(uint8_t num_rows, uint8_t current_time) {
...
     matrix_row_t existing_row = cooked[row];
     for (uint8_t col = 0; col < MATRIX_COLS; col++) {
       matrix_row_t col_mask = (ROW_SHIFTER << col);
-      if ((delta & col_mask) && *debounce_pointer == DEBOUNCE_ELAPSED) {
-        *debounce_pointer    = current_time;
-        counters_need_update = true;
-        existing_row ^= col_mask;  // flip the bit.
+      if (delta & col_mask) {
+        if (*debounce_pointer == DEBOUNCE_ELAPSED) {
+        counters_need_update = true;	          *debounce_pointer    = current_time;
```
Comment (noroadsleft) [inline quantum/debounce/eager_pk.c]: Style points available here.

```suggestion
          counters_need_update = true;
          *debounce_pointer    = current_time;
```

Comment (drashna) [reply quantum/debounce/eager_pk.c]: Actually, this entire line needs to be removed, as it's redundant.

Comment (noroadsleft) [reply quantum/debounce/eager_pk.c]: LOL, I was only looking at the file deltas.
